language: node_js
node_js:
  - '0.11.14'

addons:
  postgresql: "9.3"

before_install: "npm install --build-from-source"

before_script:
  - "mysql -e 'create database cnpmjs_test;'"
  - "psql -c 'create database cnpmjs_test;' -U root"

script: "make test-travis-all"


matrix:
  fast_finish: true
  include:
    - node_js: "0.11"
      env: COVERAGE=true
  allow_failures:
    - node_js: "0.11"
      env: COVERAGE=true

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
